// Generated by CoffeeScript 1.10.0
(function() {
  var BrowserWindow, app, createWindow, electron, fs, mainWindow;

  electron = require('electron');

  app = electron.app;

  BrowserWindow = electron.BrowserWindow;

  fs = require('fs');

  mainWindow = void 0;

  createWindow = function() {
    mainWindow = new BrowserWindow({
      width: 800,
      height: 600
    });
    mainWindow.setMenu(null);
    mainWindow.loadURL("file://" + __dirname + "/index.html");
    mainWindow.webContents.openDevTools();
    return mainWindow.on('closed', function() {
      return mainWindow = void 0;
    });
  };

  app.on('ready', createWindow);

  app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
      return app.quit();
    }
  });

  app.on('activate', function() {
    if (!mainWindow) {
      return createWindow();
    }
  });

}).call(this);
//声明一个保存文件的窗口
const ipc = require('electron').ipcMain;
const dialog = require('electron').dialog;
ipc.on('save-dialog', function (event) {
    const options = {
        title: '导出卫星模型',
        filters: [
            { name: 'Model', extensions: ['scene'] }
        ]
    };
    dialog.showSaveDialog(options, function (filename) {
        event.sender.send('saved-file', filename);
    })
});
//# sourceMappingURL=main.js.map
